'use client';

import { useState, useRef, useCallback, useEffect } from 'react';
import { Icon } from '@/components/ui/Icon';
import { synthesizeSpeech, assessPronunciation, fetchPracticeText, type PronunciationResult, type PracticeText } from '@/lib/api';
import { isRecordingSupported, requestMicPermission, startRecording } from '@/lib/audioRecorder';

interface PracticePanelProps {
    hskLevel: number;
    onPracticeComplete?: (result: PronunciationResult) => void;
}

export default function PracticePanel({ hskLevel, onPracticeComplete }: PracticePanelProps) {
    const [practiceText, setPracticeText] = useState<PracticeText | null>(null);
    const [isRecording, setIsRecording] = useState(false);
    const [isProcessing, setIsProcessing] = useState(false);
    const [isPlayingSample, setIsPlayingSample] = useState(false);
    const [isPlayingFeedback, setIsPlayingFeedback] = useState(false);
    const [result, setResult] = useState<PronunciationResult | null>(null);

    const recorderRef = useRef<{ stop: () => Promise<Blob>; cancel: () => void } | null>(null);
    const sampleAudioRef = useRef<HTMLAudioElement | null>(null);
    const feedbackAudioRef = useRef<HTMLAudioElement | null>(null);

    // Load new practice text — Groq-generated by default (diverse + level-appropriate length)
    const loadNewText = useCallback(async () => {
        try {
            const text = await fetchPracticeText(hskLevel);
            setPracticeText(text);
            setResult(null);
        } catch (error) {
            console.error('Failed to load practice text:', error);
            // Fallback mock data if API fails
            const mockTexts: Record<number, PracticeText[]> = {
                1: [
                    { id: 1, text: '你好', pinyin: 'nǐ hǎo', meaning: 'Xin chào' },
                    { id: 2, text: '谢谢', pinyin: 'xiè xie', meaning: 'Cảm ơn' },
                ],
                2: [
                    { id: 3, text: '我想学中文', pinyin: 'wǒ xiǎng xué zhōng wén', meaning: 'Tôi muốn học tiếng Trung' },
                ],
                3: [
                    { id: 4, text: '我每天早上七点起床', pinyin: 'wǒ měi tiān zǎo shang qī diǎn qǐ chuáng', meaning: 'Tôi mỗi ngày sáng 7 giờ dậy' },
                    { id: 5, text: '我喜欢吃中国菜', pinyin: 'wǒ xǐ huan chī zhōng guó cài', meaning: 'Tôi thích ăn món Trung Quốc' },
                ],
                4: [
                    { id: 6, text: '我对中国文化很感兴趣', pinyin: 'wǒ duì zhōng guó wén huà hěn gǎn xìng qù', meaning: 'Tôi rất quan tâm đến văn hóa Trung Quốc' },
                    { id: 7, text: '这个决定对我来说很重要', pinyin: 'zhè ge jué dìng duì wǒ lái shuō hěn zhòng yào', meaning: 'Quyết định này rất quan trọng đối với tôi' },
                ],
                5: [
                    { id: 8, text: '随着科技的发展，人们的生活方式发生了很大变化', pinyin: 'suí zhe kē jì de fā zhǎn, rén men de shēng huó fāng shì fā shēng le hěn dà biàn huà', meaning: 'Với sự phát triển của công nghệ, lối sống của con người đã thay đổi rất nhiều' },
                    { id: 9, text: '这个问题的解决需要多方面的合作', pinyin: 'zhè ge wèn tí de jiě jué xū yào duō fāng miàn de hé zuò', meaning: 'Việc giải quyết vấn đề này cần sự hợp tác từ nhiều phía' },
                ],
                6: [
                    { id: 10, text: '在当今全球化的背景下，跨文化交流变得越来越重要', pinyin: 'zài dāng jīn quán qiú huà de bèi jǐng xià, kuà wén huà jiāo liú biàn de yuè lái yuè zhòng yào', meaning: 'Trong bối cảnh toàn cầu hóa hiện nay, giao lưu văn hóa trở nên ngày càng quan trọng' },
                    { id: 11, text: '这个理论在实践中得到了充分的验证', pinyin: 'zhè ge lǐ lùn zài shí jiàn zhōng dé dào le chōng fèn de yàn zhèng', meaning: 'Lý thuyết này đã được kiểm chứng đầy đủ trong thực tế' },
                ],
            };
            const texts = mockTexts[hskLevel] || mockTexts[1];
            const randomText = texts[Math.floor(Math.random() * texts.length)];
            setPracticeText(randomText);
            setResult(null);
        }
    }, [hskLevel]);

    // Play sample audio
    const playSample = useCallback(async () => {
        if (!practiceText || isPlayingSample) return;

        try {
            setIsPlayingSample(true);
            const audioBlob = await synthesizeSpeech(practiceText.text);
            const audioUrl = URL.createObjectURL(audioBlob);
            const audio = new Audio(audioUrl);
            sampleAudioRef.current = audio;

            audio.onended = () => {
                setIsPlayingSample(false);
                URL.revokeObjectURL(audioUrl);
                sampleAudioRef.current = null;
            };

            audio.onerror = () => {
                setIsPlayingSample(false);
                URL.revokeObjectURL(audioUrl);
                sampleAudioRef.current = null;
            };

            await audio.play();
        } catch (error) {
            console.error('Failed to play sample:', error);
            setIsPlayingSample(false);
        }
    }, [practiceText, isPlayingSample]);

    // Play feedback audio from text (for auto-play after assessment)
    const playFeedbackAudio = useCallback(async (feedbackText: string) => {
        if (!feedbackText || isPlayingFeedback) return;

        try {
            setIsPlayingFeedback(true);
            const audioBlob = await synthesizeSpeech(feedbackText);
            const audioUrl = URL.createObjectURL(audioBlob);
            const audio = new Audio(audioUrl);
            feedbackAudioRef.current = audio;

            audio.onended = () => {
                setIsPlayingFeedback(false);
                URL.revokeObjectURL(audioUrl);
                feedbackAudioRef.current = null;
            };

            audio.onerror = () => {
                setIsPlayingFeedback(false);
                URL.revokeObjectURL(audioUrl);
                feedbackAudioRef.current = null;
            };

            await audio.play();
        } catch (error) {
            console.error('Failed to play feedback:', error);
            setIsPlayingFeedback(false);
        }
    }, [isPlayingFeedback]);

    // Play feedback audio
    const playFeedback = useCallback(async () => {
        if (!result?.feedback || isPlayingFeedback) return;

        try {
            setIsPlayingFeedback(true);
            const audioBlob = await synthesizeSpeech(result.feedback);
            const audioUrl = URL.createObjectURL(audioBlob);
            const audio = new Audio(audioUrl);
            feedbackAudioRef.current = audio;

            audio.onended = () => {
                setIsPlayingFeedback(false);
                URL.revokeObjectURL(audioUrl);
                feedbackAudioRef.current = null;
            };

            audio.onerror = () => {
                setIsPlayingFeedback(false);
                URL.revokeObjectURL(audioUrl);
                feedbackAudioRef.current = null;
            };

            await audio.play();
        } catch (error) {
            console.error('Failed to play feedback:', error);
            setIsPlayingFeedback(false);
        }
    }, [result, isPlayingFeedback]);

    // Start recording
    const startRecordingHandler = useCallback(async () => {
        if (!practiceText || isRecording) return;

        const hasPermission = await requestMicPermission();
        if (!hasPermission) {
            alert('Trình duyệt chưa cấp quyền microphone. Vui lòng cho phép trong cài đặt.');
            return;
        }

        try {
            const recorder = await startRecording();
            recorderRef.current = recorder;
            setIsRecording(true);
        } catch (error) {
            console.error('Failed to start recording:', error);
            alert('Không thể truy cập microphone.');
        }
    }, [practiceText, isRecording]);

    // Stop recording and assess
    const stopRecordingHandler = useCallback(async () => {
        if (!recorderRef.current) return;

        setIsRecording(false);
        setIsProcessing(true);

        try {
            const audioBlob = await recorderRef.current.stop();
            recorderRef.current = null;

            if (audioBlob.size === 0) {
                alert('Không ghi được âm thanh. Vui lòng thử lại.');
                setIsProcessing(false);
                return;
            }

            // Assess pronunciation
            const assessmentResult = await assessPronunciation(audioBlob, practiceText!.text);
            setResult(assessmentResult);

            // Auto-play feedback (pass result directly to avoid state race condition)
            if (assessmentResult.feedback) {
                await playFeedbackAudio(assessmentResult.feedback);
            }

            // Notify parent
            if (onPracticeComplete) {
                onPracticeComplete(assessmentResult);
            }
        } catch (error) {
            console.error('Failed to assess pronunciation:', error);
            alert('Lỗi chấm phát âm. Vui lòng thử lại.');
        } finally {
            setIsProcessing(false);
        }
    }, [practiceText, onPracticeComplete, playFeedbackAudio]);

    // Cancel recording
    const cancelRecordingHandler = useCallback(() => {
        if (recorderRef.current) {
            recorderRef.current.cancel();
            recorderRef.current = null;
        }
        setIsRecording(false);
    }, []);

    // Cleanup on unmount
    useEffect(() => {
        return () => {
            recorderRef.current?.cancel();
            sampleAudioRef.current?.pause();
            feedbackAudioRef.current?.pause();
        };
    }, []);

    // Load initial text
    useEffect(() => {
        loadNewText();
    }, [loadNewText]);

    return (
        <div className="flex flex-col items-center gap-4 p-4">
            {/* Practice text display */}
            {practiceText && (
                <div className="w-full p-4 rounded-xl bg-[var(--surface)] border border-[var(--border)]">
                    <div className="text-center">
                        <div className="text-2xl font-bold text-[var(--text-main)] mb-2">
                            {practiceText.text}
                        </div>
                        <div className="text-sm text-[var(--text-secondary)] mb-1">
                            {practiceText.pinyin}
                        </div>
                        <div className="text-sm text-[var(--text-muted)]">
                            {practiceText.meaning}
                        </div>
                    </div>

                    {/* Example sentence */}
                    {practiceText.example && (
                        <div className="mt-3 p-2 rounded-lg bg-[var(--background)] text-xs text-[var(--text-secondary)]">
                            <span className="font-semibold">Ví dụ: </span>
                            {practiceText.example}
                        </div>
                    )}

                    {/* Play sample button */}
                    <button
                        onClick={playSample}
                        disabled={isPlayingSample || isRecording || isProcessing}
                        className="mt-3 w-full py-2 rounded-lg bg-[var(--surface-secondary)] text-[var(--text-secondary)] hover:text-[var(--text-main)] transition-colors disabled:opacity-50"
                    >
                        <Icon name={isPlayingSample ? 'volume_up' : 'play_circle'} size="sm" className="mr-2" />
                        {isPlayingSample ? 'Đang nghe mẫu...' : 'Nghe mẫu'}
                    </button>
                </div>
            )}

            {/* Recording controls */}
            <div className="flex items-center gap-4">
                <button
                    onClick={isRecording ? stopRecordingHandler : startRecordingHandler}
                    disabled={!practiceText || isProcessing || !!result}
                    className={`w-16 h-16 rounded-full flex items-center justify-center transition-all ${
                        isRecording
                            ? 'bg-[var(--error)] text-white'
                            : 'bg-[var(--primary)] text-white hover:bg-[var(--primary-hover)]'
                    } disabled:opacity-50`}
                >
                    <Icon name={isRecording ? 'stop' : 'mic'} size="lg" />
                </button>

                {isRecording && (
                    <button
                        onClick={cancelRecordingHandler}
                        className="w-10 h-10 rounded-full bg-[var(--surface-secondary)] border border-[var(--border)] text-[var(--text-muted)] hover:text-[var(--error)] transition-colors"
                    >
                        <Icon name="close" size="sm" />
                    </button>
                )}
            </div>

            {/* Status text */}
            <p className="text-xs text-[var(--text-muted)]">
                {isRecording ? 'Đang ghi âm... nhấn để dừng' :
                 isProcessing ? 'Đang chấm điểm...' :
                 result ? 'Hoàn thành!' :
                 'Nhấn mic và đọc theo mẫu'}
            </p>

            {/* Result display */}
            {result && (
                <div className="w-full p-4 rounded-xl bg-[var(--surface)] border border-[var(--border)]">
                    {/* Score */}
                    <div className="text-center mb-4">
                        <div className={`text-3xl font-bold ${
                            result.pronunciationScore >= 85 ? 'text-emerald-600' :
                            result.pronunciationScore >= 70 ? 'text-amber-500' :
                            'text-red-500'
                        }`}>
                            {Math.round(result.pronunciationScore)}/100
                        </div>
                    </div>

                    {/* Sub-scores */}
                    <div className="grid grid-cols-3 gap-2 mb-3">
                        {[
                            ['Chính xác', result.accuracyScore],
                            ['Lưu loát', result.fluencyScore],
                            ['Hoàn chỉnh', result.completenessScore]
                        ].map(([label, score]) => (
                            <div key={label as string} className="text-center">
                                <div className="text-[var(--text-muted)] text-xs">{label as string}</div>
                                <div className="font-semibold text-[var(--text-main)]">{Math.round(score as number)}</div>
                            </div>
                        ))}
                    </div>

                    {/* Weak phonemes */}
                    {result.weakPhonemes && result.weakPhonemes.length > 0 && (
                        <div className="mb-3">
                            <div className="text-sm font-semibold text-[var(--text-main)] mb-2">
                                Cần cải thiện:
                            </div>
                            <div className="flex flex-wrap gap-1.5">
                                {result.weakPhonemes.map((p, idx) => (
                                    <span
                                        key={idx}
                                        className="px-2 py-0.5 rounded-md bg-amber-100 text-amber-700 text-xs font-medium"
                                    >
                                        {p.word} ({p.phoneme})
                                    </span>
                                ))}
                            </div>
                        </div>
                    )}

                    {/* Feedback — Vietnamese first (primary, what learner actually reads),
                        Chinese after (secondary, also what TTS will play). */}
                    {(result.feedbackVi || result.feedback) && (
                        <div className="p-3 rounded-lg bg-[var(--background)] mb-3 space-y-2">
                            {result.feedbackVi && (
                                <p className="text-sm text-[var(--text-main)] leading-relaxed">
                                    {result.feedbackVi}
                                </p>
                            )}
                            {result.feedback && (
                                <p className="text-xs text-[var(--text-muted)] leading-relaxed">
                                    {result.feedback}
                                </p>
                            )}
                        </div>
                    )}

                    {/* Play feedback button — TTS reads the Chinese version */}
                    {result.feedback && (
                        <button
                            onClick={playFeedback}
                            disabled={isPlayingFeedback}
                            className="w-full py-2 rounded-lg bg-[var(--surface-secondary)] text-[var(--text-secondary)] hover:text-[var(--text-main)] transition-colors disabled:opacity-50"
                        >
                            <Icon name={isPlayingFeedback ? 'volume_up' : 'play_circle'} size="sm" className="mr-2" />
                            {isPlayingFeedback ? 'Đang nghe hướng dẫn...' : 'Nghe hướng dẫn (Trung)'}
                        </button>
                    )}

                    {/* Retry button */}
                    <button
                        onClick={() => {
                            setResult(null);
                            loadNewText();
                        }}
                        className="mt-2 w-full py-2 rounded-lg bg-[var(--primary)] text-white hover:bg-[var(--primary-hover)] transition-colors"
                    >
                        Thử câu khác
                    </button>
                </div>
            )}
        </div>
    );
}